variable "ssh_key_name" {
  description = "The name of the .pem file in the ~/.ssh folder"
  type        = string
  default     = "craftista-key"
}

locals {

  ssh_user = "ubuntu"

  craft_instances = {
    "frontend"       = aws_instance.frontend.private_ip
    "voting"         = aws_instance.voting.private_ip
    "recommendation" = aws_instance.recommendation.private_ip
    "catalogue"      = aws_instance.catalogue.private_ip
  }
}

resource "local_file" "ssh_config" {
  filename = "${path.module}/ssh_config"
  content  = <<-EOT
    # AUTO-GENERATED BY TERRAFORM - DO NOT EDIT MANUALLY

    # The Gateway (Bastion)
    Host bastion
      HostName ${aws_eip.eip-bastion.public_ip}
      User ${local.ssh_user}
      IdentityFile ~/.ssh/${var.ssh_key_name}
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null

    # The Craft Stack Shortcuts
    %{for name, ip in local.craft_instances~}
    Host craft-${name}
      HostName ${ip}
      ProxyJump bastion
      User ${local.ssh_user}
      IdentityFile ~/.ssh/${var.ssh_key_name}
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
    %{endfor~}
  EOT
}